name: Release
on:
  push:
    branches: ["main"]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@4
        with:
          cache: npm
          node-version: "lts/*"
      - run: yarn install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

